kind: pipeline
name: build

steps:
  - name: webpack-build
    image: nextcloudci/node:node-4
    commands:
      - npm ci
      - npm run build
      - git status
      - bash -c "[[ ! \"`git status --porcelain `\" ]] || ( echo 'Uncommited changes in webpack build' && exit 1 )"

trigger:
  branch:
    - master
    - stable*

