language: php
php:
  - 5.6
  - 7

env:
  global:
    - CORE_BRANCH=stable11
    - APP=files_texteditor
  matrix:
    - DB=sqlite

branches:
  only:
    - master
    - /^stable\d+(\.\d+)?$/

before_install:
  - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh 
  - bash ./before_install.sh $APP $CORE_BRANCH $DB
  - cd ../server
  - php occ app:enable $APP

before_script:
  - cd apps/$APP

script:
  # Test lint
  - find . -name \*.php -not -path './vendor/*' -exec php -l "{}" \;

  # Run phpunit tests
  - cd tests
  - phpunit --configuration phpunit.xml

  # Create coverage report
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover clover.xml

matrix:
  fast_finish: true
