language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7

env:
  global:
    - CORE_BRANCH=master
    - APP=files_texteditor
  matrix:
    - DB=sqlite

branches:
  only:
    - master
    - /^stable\d+(\.\d+)?$/

before_install:
  - wget https://raw.githubusercontent.com/owncloud/administration/master/travis-ci/before_install.sh
  - bash ./before_install.sh $APP $CORE_BRANCH $DB
  - cd ../core
  - php occ app:enable $APP

before_script:
  - cd apps/$APP

script:
  # Test lint
  - find . -name \*.php -not -path './vendor/*' -exec php -l "{}" \;

  # Run phpunit tests
  - cd tests
  - phpunit --configuration phpunit.xml

  # Create coverage report
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover clover.xml

matrix:
  include:
    - php: 5.4
      env: "DB=mysql CORE_BRANCH=stable8"
    - php: 5.4
      env: "DB=mysql CORE_BRANCH=stable8.1"

  fast_finish: true
